version: '3'
services:
  senseive-reader:
    image: ghcr.io/simbarras/3sigmas-monitorvisualization/senseive-reader:main-0.0.5
    restart: always
    environment:
      - INFLUX_TOKEN=-LSlQXq0uRiNrRuO5gtRg8g75aCU8_9S7ez2tGnfVjQBBaUkby_mXkpQSI9qqoxY0KF1EfGfnevwR6Uo4zG35g==
      - INFLUX_URL=http://192.168.1.158:8086
      - INFLUX_ORG=3sigmas
      - FTP_SERVER_URL=ftp.cluster020.hosting.ovh.net
      - FTP_SERVER_PATH=/grafana
      - FTP_USER=sigmaschcy-guest
      - FTP_PASSWORD=GUEST3sigmas
    volumes:
      - senseive_data:/backup

volumes:
  senseive_data: {}