version: "3"

networks:
  monitoring:

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - 8086:8086
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.1.1
    ports:
      - 3000:3000
    networks:
      - monitoring